/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as JarRouteImport } from './routes/jar'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LooksRouteImport } from './routes/looks'
import { Route as PileRouteImport } from './routes/pile'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ReelRouteImport } from './routes/reel'
import { Route as ShipRouteImport } from './routes/ship'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEbayCallbackRouteImport } from './routes/api/ebay/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const JarRoute = JarRouteImport.update({
  id: '/jar',
  path: '/jar',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksRoute = LooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const PileRoute = PileRouteImport.update({
  id: '/pile',
  path: '/pile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelRoute = ReelRouteImport.update({
  id: '/reel',
  path: '/reel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipRoute = ShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbayCallbackRoute = ApiEbayCallbackRouteImport.update({
  id: '/api/ebay/callback',
  path: '/api/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/crew': typeof CrewRoute
  '/desk': typeof DeskRoute
  '/hunt': typeof HuntRoute
  '/inventory': typeof InventoryRoute
  '/jar': typeof JarRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/looks': typeof LooksRoute
  '/pile': typeof PileRoute
  '/playbook': typeof PlaybookRoute
  '/reel': typeof ReelRoute
  '/ship': typeof ShipRoute
  '/story': typeof StoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/crew': typeof CrewRoute
  '/desk': typeof DeskRoute
  '/hunt': typeof HuntRoute
  '/inventory': typeof InventoryRoute
  '/jar': typeof JarRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/looks': typeof LooksRoute
  '/pile': typeof PileRoute
  '/playbook': typeof PlaybookRoute
  '/reel': typeof ReelRoute
  '/ship': typeof ShipRoute
  '/story': typeof StoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/crew': typeof CrewRoute
  '/desk': typeof DeskRoute
  '/hunt': typeof HuntRoute
  '/inventory': typeof InventoryRoute
  '/jar': typeof JarRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/looks': typeof LooksRoute
  '/pile': typeof PileRoute
  '/playbook': typeof PlaybookRoute
  '/reel': typeof ReelRoute
  '/ship': typeof ShipRoute
  '/story': typeof StoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/channels'
    | '/connect'
    | '/crew'
    | '/desk'
    | '/hunt'
    | '/inventory'
    | '/jar'
    | '/listings'
    | '/login'
    | '/looks'
    | '/pile'
    | '/playbook'
    | '/reel'
    | '/ship'
    | '/story'
    | '/api/auth/$'
    | '/api/ebay/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/channels'
    | '/connect'
    | '/crew'
    | '/desk'
    | '/hunt'
    | '/inventory'
    | '/jar'
    | '/listings'
    | '/login'
    | '/looks'
    | '/pile'
    | '/playbook'
    | '/reel'
    | '/ship'
    | '/story'
    | '/api/auth/$'
    | '/api/ebay/callback'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/channels'
    | '/connect'
    | '/crew'
    | '/desk'
    | '/hunt'
    | '/inventory'
    | '/jar'
    | '/listings'
    | '/login'
    | '/looks'
    | '/pile'
    | '/playbook'
    | '/reel'
    | '/ship'
    | '/story'
    | '/api/auth/$'
    | '/api/ebay/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChannelsRoute: typeof ChannelsRoute
  ConnectRoute: typeof ConnectRoute
  CrewRoute: typeof CrewRoute
  DeskRoute: typeof DeskRoute
  HuntRoute: typeof HuntRoute
  InventoryRoute: typeof InventoryRoute
  JarRoute: typeof JarRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  LooksRoute: typeof LooksRoute
  PileRoute: typeof PileRoute
  PlaybookRoute: typeof PlaybookRoute
  ReelRoute: typeof ReelRoute
  ShipRoute: typeof ShipRoute
  StoryRoute: typeof StoryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEbayCallbackRoute: typeof ApiEbayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jar': {
      id: '/jar'
      path: '/jar'
      fullPath: '/jar'
      preLoaderRoute: typeof JarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks': {
      id: '/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof LooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pile': {
      id: '/pile'
      path: '/pile'
      fullPath: '/pile'
      preLoaderRoute: typeof PileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel': {
      id: '/reel'
      path: '/reel'
      fullPath: '/reel'
      preLoaderRoute: typeof ReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship': {
      id: '/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof ShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebay/callback': {
      id: '/api/ebay/callback'
      path: '/api/ebay/callback'
      fullPath: '/api/ebay/callback'
      preLoaderRoute: typeof ApiEbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChannelsRoute: ChannelsRoute,
  ConnectRoute: ConnectRoute,
  CrewRoute: CrewRoute,
  DeskRoute: DeskRoute,
  HuntRoute: HuntRoute,
  InventoryRoute: InventoryRoute,
  JarRoute: JarRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  LooksRoute: LooksRoute,
  PileRoute: PileRoute,
  PlaybookRoute: PlaybookRoute,
  ReelRoute: ReelRoute,
  ShipRoute: ShipRoute,
  StoryRoute: StoryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEbayCallbackRoute: ApiEbayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
